#!/usr/bin/env make --file

image=asterisk
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

# runargs=--publish-all
runargs=--publish=5060:5060/udp \
runargs=--publish=5061:5061/udp \
	--publish=17700-17710:17700-17710/udp
